REM PROGRAM THAT CREATES THE DIRECTORIES FOR ASSIGNEMENTS

@ECHO OFF

REM CREATING THE MAIN DIRECTORY
SET fold = sabaini_chiara_%1_%2_%3
MKDIR %fold%
REM CREATING THE SUB-DIRECTORIES
CD %fold%
MKDIR bin
MKDIR doc
MKDIR src

REM CREATING THE BASIC CONTENTS
CD doc
NUL> %1